//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dovido_Onay_Sitemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ANT_PROFORMA_BILGI
    {
        public int ID { get; set; }
        public string PROFORMA_NO { get; set; }
        public string AMBALAJ_TIPI { get; set; }
        public string PALET_BILGI2 { get; set; }
        public string PALET_BILGI { get; set; }
        public Nullable<int> HAFTA { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> DURUM { get; set; }
    }
}
