//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dovido_Onay_Sitemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DovidoEntitie : DbContext
    {
        public DovidoEntitie()
            : base("name=DovidoEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_ANT_PROFORMA_BILGI> C_ANT_PROFORMA_BILGI { get; set; }
        public virtual DbSet<C_ANTE_DOVIDO_PROFORMA> C_ANTE_DOVIDO_PROFORMA { get; set; }
        public virtual DbSet<C_ANTE_PROFORMA_LIST> C_ANTE_PROFORMA_LIST { get; set; }
    }
}
